/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDeliverySheetRouteImport } from './routes/_authenticated/delivery-sheet'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkuOpportunityRouteImport } from './routes/_authenticated/sku-opportunity'
import { Route as AuthenticatedShopsIndexRouteImport } from './routes/_authenticated/shops.index'
import { Route as AuthenticatedShopsShopIdRouteImport } from './routes/_authenticated/shops.$shopId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliverySheetRoute =
  AuthenticatedDeliverySheetRouteImport.update({
    id: '/delivery-sheet',
    path: '/delivery-sheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkuOpportunityRoute =
  AuthenticatedSkuOpportunityRouteImport.update({
    id: '/sku-opportunity',
    path: '/sku-opportunity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopsIndexRoute = AuthenticatedShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopsShopIdRoute =
  AuthenticatedShopsShopIdRouteImport.update({
    id: '/shops/$shopId',
    path: '/shops/$shopId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/delivery-sheet': typeof AuthenticatedDeliverySheetRoute
  '/import': typeof AuthenticatedImportRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sku-opportunity': typeof AuthenticatedSkuOpportunityRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/shops/': typeof AuthenticatedShopsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/delivery-sheet': typeof AuthenticatedDeliverySheetRoute
  '/import': typeof AuthenticatedImportRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sku-opportunity': typeof AuthenticatedSkuOpportunityRoute
  '/': typeof AuthenticatedIndexRoute
  '/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/shops': typeof AuthenticatedShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/delivery-sheet': typeof AuthenticatedDeliverySheetRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sku-opportunity': typeof AuthenticatedSkuOpportunityRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/shops/$shopId': typeof AuthenticatedShopsShopIdRoute
  '/_authenticated/shops/': typeof AuthenticatedShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/costs'
    | '/deliveries'
    | '/delivery-sheet'
    | '/import'
    | '/labels'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sku-opportunity'
    | '/shops/$shopId'
    | '/shops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/costs'
    | '/deliveries'
    | '/delivery-sheet'
    | '/import'
    | '/labels'
    | '/orders'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sku-opportunity'
    | '/'
    | '/shops/$shopId'
    | '/shops'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/costs'
    | '/_authenticated/deliveries'
    | '/_authenticated/delivery-sheet'
    | '/_authenticated/import'
    | '/_authenticated/labels'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/sku-opportunity'
    | '/_authenticated/'
    | '/_authenticated/shops/$shopId'
    | '/_authenticated/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-sheet': {
      id: '/_authenticated/delivery-sheet'
      path: '/delivery-sheet'
      fullPath: '/delivery-sheet'
      preLoaderRoute: typeof AuthenticatedDeliverySheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sku-opportunity': {
      id: '/_authenticated/sku-opportunity'
      path: '/sku-opportunity'
      fullPath: '/sku-opportunity'
      preLoaderRoute: typeof AuthenticatedSkuOpportunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shops/': {
      id: '/_authenticated/shops/'
      path: '/shops'
      fullPath: '/shops/'
      preLoaderRoute: typeof AuthenticatedShopsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shops/$shopId': {
      id: '/_authenticated/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof AuthenticatedShopsShopIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedDeliverySheetRoute: typeof AuthenticatedDeliverySheetRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkuOpportunityRoute: typeof AuthenticatedSkuOpportunityRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedShopsShopIdRoute: typeof AuthenticatedShopsShopIdRoute
  AuthenticatedShopsIndexRoute: typeof AuthenticatedShopsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedDeliverySheetRoute: AuthenticatedDeliverySheetRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkuOpportunityRoute: AuthenticatedSkuOpportunityRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedShopsShopIdRoute: AuthenticatedShopsShopIdRoute,
  AuthenticatedShopsIndexRoute: AuthenticatedShopsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
